name: flake8
on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r just_because/requirements.txt
    - name: run flake8
      run: |
        export PYTHONPATH='.'
        flake8 just_because testcases
